---
name: "Bella G"
title: "epi590r"
format: html
editor: visual
echo: false 
---

```{r}
#downloading packages
 

library(readr)
library(tidyverse)
library(gtsummary)
library(dplyr)
install.packages("broom.helpers")
library(broom.helpers)
install.packages("cards")
library("cards")
```

```{r}
#uploading covid dataset
install.packages("medicaldata")
library(medicaldata)
data(package="medicaldata")
covid <- medicaldata::covid_testing
class(covid)
covid <- as.data.frame(covid)

write_csv(covid, here::here("Data", "raw", "covid.csv"))


#cleaning data
covid_clean <- covid |>
  mutate(clinic_name = case_when(str_detect(clinic_name, "onc") ~ "oncology",str_detect(clinic_name, "mri") ~ "MRI", str_detect(clinic_name, "onc") ~ "oncology", str_detect(clinic_name, "rad") ~ "diagnosis radiology",str_detect(clinic_name, "urg") ~ "urgent care",
           str_detect(clinic_name, "lab") ~ "laboratory",str_detect(clinic_name, "ntwk") ~ "care network",
           str_detect(clinic_name, "hosp") ~ "hospital",
           str_detect(clinic_name, "ward") ~ "ward",
           TRUE ~ clinic_name 
         ),
         clinic_name = fct_lump(clinic_name, n = 10))

write_rds(covid_clean, here::here("R", "covid_clean.rds"))
write_csv(covid_clean, here::here("Data", "clean", "covid_clean.csv"))
```

```{r}
library(gtsummary)
library(broom)
library(broom.helpers)


 table <- tbl_summary(
  data = covid_clean,
  by = gender,
  include = c(age, result, pan_day, test_id, clinic_name, payor_group, demo_group, patient_class),
  label = list(
    payor_group ~ "Paying method",
    pan_day ~ "# of days tested after pandemic start",
    test_id ~ "Type of test",
    clinic_name ~ "Clinic",
    demo_group ~ "Subject groups", 
    patient_class ~ "Subject disposition" 
  ),
  missing = "no")   |> 
 	add_overall(col_label = "**Total**") |> 
  bold_labels() 
 
 table
```

```{r}
#regression model
library(cardx)

regressionmodel <- tbl_uvregression(
  covid_clean,
  y=age, 
  method = lm,
  include = c(age, clinic_name,result, gender, payor_group, demo_group, patient_class)
)

regressionmodel

#fix below

inline_text(regressionmodel, variable= "payor_group")

```

```{r}
#create function of sample std
stdfunction <- function(col_rec_tat) {
  n <- length(col_rec_tat)            
  mean <- sum(col_rec_tat) / n          
  diffsq <- (col_rec_tat - mean)^2       
  variance <- sum(diffsq) / (n - 1)      
  std_val <- sqrt(variance)                      
  
  return(std_val)
}

sd(covid_clean$col_rec_tat, na.rm=TRUE)
stdfunction(covid_clean$col_rec_tat)

```

We are 95% confident that the true mean height of the population lies between (`ci`)

```{r}
#i stopped here
#| label: fig-hist
#| fig-cap: "This is a histogram"
hist(covid_clean$age, main= "Histogram of Age", 
     xlab = "Age", 
     ylab = "Frequency", 
     col = "coral",
     border = "black")
```

```{r}
#inline text
ci<-inline_text(model, variable="pan_day", pattern = "{estimate} ({conf.low}, {conf.high})")


}
```
